name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:


    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      env: 
        GO111MODULE: on
      run: |
        go get -v -t -d ./...

    - name: Test
      run: go test -v ./...

    - name: Build as binary
      run: GOOS=windows GOARCH=amd64 go build -o ./dist/vrc_auto_rejoin_tool_x64.exe ./cli/

    - name: Achive to zip
      run:
        powershell compress-archive -Path dist/vrc_auto_rejoin_tool_x64.exe -DestinationPath dist/vrc_auto_rejoin_tool_x64.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "dist/**"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
